# Generated by Django 2.0.3 on 2018-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=20)),
                ('graded', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
    ]
