# Generated by Django 2.0.3 on 2018-04-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='publisher',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
