# Generated by Django 2.0.3 on 2018-04-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_comic_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['-id']},
        ),
    ]
