# Generated by Django 2.0.3 on 2018-04-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_auto_20180405_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='issue',
            field=models.CharField(max_length=100),
        ),
    ]
